services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: ghcr.io/netvpc/nodebb:latest
    volumes:
      - nodebb-config:/opt/config
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-modules:/usr/src/app/node_modules
    environment:
      OVERRIDE_UPDATE_LOCK: true

volumes:
  nodebb-config:
  nodebb-build:
  nodebb-uploads:
  nodebb-modules:
  mongo-data: