services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: test
    volumes:
      - nodebb-config:/opt/config
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-modules:/usr/src/app/node_modules
      - ./setup.json:/usr/src/app/setup.json
    environment:
      OVERRIDE_UPDATE_LOCK: true
      START_BUILD: true

volumes:
  nodebb-config:
  nodebb-build:
  nodebb-uploads:
  nodebb-modules:
  mongo-data: